#' Parallel processing form of batch_snf
#'
#' @param data_list nested list of input data generated by the function
#' `get_data_list()`.
#'
#' @param distance_metrics_list An optional nested list containing which
#' distance metric function should be used for the various variable types
#' (continuous, discrete, ordinal, categorical, and mixed). See
#' ?generate_distance_metrics_list for details on how to build this.
#'
#' @param clust_algs_list List of custom clustering algorithms to apply
#' to the final fused network. See ?generate_clust_algs_list.
#'
#' @param settings_matrix matrix indicating parameters to iterate SNF through.
#'
#' @param weights_matrix A matrix containing variable weights to use during
#'  distance matrix calculation. See ?generate_weights_matrix for details on
#'  how to build this.
#'
#' @param processes Number of parallel processes used when executing SNF.
#'
#' @return populated_settings_matrix settings matrix with filled columns
#' related to subtype membership.
#'
#' @export
parallel_batch_snf <- function(data_list,
                               distance_metrics_list,
                               clust_algs_list,
                               settings_matrix,
                               weights_matrix,
                               processes) {
    future::plan(future::multisession, workers = processes)
    batch_row_function <- batch_row_closure(
        data_list = data_list,
        distance_metrics_list = distance_metrics_list,
        clust_algs_list = clust_algs_list,
        settings_matrix = settings_matrix,
        weights_matrix = weights_matrix
    )
    settings_and_weights_df <- cbind(settings_matrix, weights_matrix)
    solutions_matrix <- future.apply::future_apply(
        settings_and_weights_df,
        1,
        batch_row_function
    )
    solutions_matrix <- do.call("rbind", solutions_matrix)
    solutions_matrix <- solutions_matrix |> unique()
    solutions_matrix <- numcol_to_numeric(solutions_matrix)
    future::plan(future::sequential)
    return(solutions_matrix)
}

#' Generate closure function to run batch_snf in an apply-friendly format
#'
#' @param data_list nested list of input data generated by the function
#' `get_data_list()`.
#'
#' @param distance_metrics_list An optional nested list containing which
#' distance metric function should be used for the various variable types
#' (continuous, discrete, ordinal, categorical, and mixed). See
#' ?generate_distance_metrics_list for details on how to build this.
#'
#' @param clust_algs_list List of custom clustering algorithms to apply
#' to the final fused network. See ?generate_clust_algs_list.
#'
#' @param settings_matrix matrix indicating parameters to iterate SNF through.
#'
#' @param weights_matrix A matrix containing variable weights to use during
#'  distance matrix calculation. See ?generate_weights_matrix for details on
#'  how to build this.
#'
#' @export
batch_row_closure <- function(data_list,
                              distance_metrics_list,
                              clust_algs_list,
                              settings_matrix,
                              weights_matrix) {
    settings_matrix_names <- colnames(settings_matrix)
    weights_matrix_names <- colnames(weights_matrix)
    row_function <- function(settings_and_weights_row) {
        settings_and_weights_row_df <- data.frame(t(settings_and_weights_row))
        settings_matrix_row <- settings_and_weights_row_df[, settings_matrix_names]
        weights_row <- settings_and_weights_row_df[, weights_matrix_names]
        # Reduce data list
        current_data_list <- drop_inputs(settings_matrix_row, data_list)
        # Extract parameters for snf_step
        current_snf_scheme <- dplyr::case_when(
            settings_matrix_row$"snf_scheme" == 1 ~ "individual",
            settings_matrix_row$"snf_scheme" == 2 ~ "domain",
            settings_matrix_row$"snf_scheme" == 3 ~ "twostep",
        )
        k <- settings_matrix_row$"k"
        alpha <- settings_matrix_row$"alpha"
        t <- settings_matrix_row$"t"
        cont_dist <- settings_matrix_row$"cont_dist"
        disc_dist <- settings_matrix_row$"disc_dist"
        ord_dist <- settings_matrix_row$"ord_dist"
        cat_dist <- settings_matrix_row$"cat_dist"
        mix_dist <- settings_matrix_row$"mix_dist"
        cont_dist_fn <- distance_metrics_list$"continuous_distance"[[cont_dist]]
        disc_dist_fn <- distance_metrics_list$"discrete_distance"[[disc_dist]]
        ord_dist_fn <- distance_metrics_list$"ordinal_distance"[[ord_dist]]
        cat_dist_fn <- distance_metrics_list$"categorical_distance"[[cat_dist]]
        mix_dist_fn <- distance_metrics_list$"mixed_distance"[[mix_dist]]
        # Integrate data
        fused_network <- snf_step(
            current_data_list,
            current_snf_scheme,
            k = k,
            alpha = alpha,
            t = t,
            cont_dist_fn = cont_dist_fn,
            disc_dist_fn = disc_dist_fn,
            ord_dist_fn = ord_dist_fn,
            cat_dist_fn = cat_dist_fn,
            mix_dist_fn = mix_dist_fn,
            weights_row = weights_row
        )
        ## Write similarity matrices if requested
        #if (!is.null(similarity_matrix_dir)) {
        #    row_id <- settings_matrix_row$"row_id"
        #    utils::write.csv(
        #        x = fused_network,
        #        file = similarity_matrix_path(similarity_matrix_dir, row_id),
        #        row.names = TRUE
        #    )
        #}
        clust_alg <- clust_algs_list[[settings_matrix_row$"clust_alg"]]
        print(clust_algs_list)
        # cluster_results is a named list containing the cluster solution
        #  (vector of which cluster each patient was assigned to) and the
        #  number of clusters for that solution
        cluster_results <- clust_alg(fused_network)
        solution <- cluster_results$"solution"
        nclust <- cluster_results$"nclust"
        settings_matrix_row[1, rownames(fused_network)] <- solution
        settings_matrix_row$"nclust" <- nclust
        return(settings_matrix_row)
    }
    return(row_function)
}

#' Apply-based function for batch_snf
#'
#' @param settings_matrix_row a row of a settings matrix
#' @param dl a data list
#'
#' @return solutions_matrix_row the corresponding solutions_matrix row
#'
#' @export
batch_snf_row_fn <- function(settings_matrix_row, data_list) {
    settings_matrix_row <- data.frame(t(settings_matrix_row))
    current_data_list <- drop_inputs(settings_matrix_row, data_list)
    current_snf_scheme <- dplyr::case_when(
        settings_matrix_row$"snf_scheme" == 1 ~ "individual",
        settings_matrix_row$"snf_scheme" == 2 ~ "domain",
        settings_matrix_row$"snf_scheme" == 3 ~ "twostep",
    )
    k <- settings_matrix_row$"k"
    alpha <- settings_matrix_row$"alpha"
    t <- settings_matrix_row$"t"
    fused_network <- snf_step(
        current_data_list,
        current_snf_scheme,
        k = k,
        alpha = alpha)
    all_clust <- SNFtool::estimateNumberOfClustersGivenGraph(fused_network)
    # Apply the current row's number of clusters heuristic
    if (settings_matrix_row$"eigen_or_rot" == 1) {
        eigen_best <- all_clust$`Eigen-gap best`
        nclust <- eigen_best
    } else if (settings_matrix_row$"eigen_or_rot" == 2) {
        rot_best <- all_clust$`Rotation cost best`
        nclust <- rot_best
    }
    settings_matrix_row$"nclust" <- nclust
    cluster_results <- SNFtool::spectralClustering(fused_network, nclust)
    # Assign subtype membership
    settings_matrix_row[1, rownames(fused_network)] <- cluster_results
    return(settings_matrix_row)
}
